[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["nvidia/label/cuda-11.8.0","nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "TEMCA"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pip = "*"
setuptools = "*"
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0" }
pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
pytorch-cuda = { version = "11.8", channel = "pytorch" }
pyyaml = "*"
tqdm = "*"
tensorboardX = "*"
einops = "*"
timm = "*"
scikit-learn = "*"
scipy = "*"
matplotlib = "*"
numpy = "<2"
hydra-core = "*"
omegaconf = "*"
mkl = "2024.0"
networkx = "*"

[pypi-dependencies]
giotto-ph = "*"